[package]
authors = ["Cloudflare Workers Team <workers@cloudflare.com>"]
edition = "2018"
name = "worker-build"
version = "0.0.5"
license = "Apache-2.0"
repository = "https://github.com/cloudflare/workers-rs/tree/main/worker-build"
readme = "README.md"
description = "This is a tool to be used as a custom build command for a Cloudflare Workers `workers-rs` project."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
swc = "0.185.0"
swc_bundler = "0.150.0"
swc_common = "0.18.8"
swc_ecma_codegen = "0.109.1"
swc_ecma_loader = "0.30.2"
swc_ecma_parser = "0.105.0"

[dev-dependencies]
tempdir = "0.3.7"
wasm-bindgen-cli-support = "0.2.80"
