name = "do-test-rust"
type = "javascript"

workers_dev = true
kv_namespaces = [
  { binding = "SOME_NAMESPACE", id = "e019ce08616d48f2a498e49fe0c51be2" },
  { binding = "SOME_KV", id = "23e78ed5402541b4a8c1bffef4726408" }
]
vars = { SOME_VARIABLE = "some value" }

[build]
command = "rust-worker-build"

[build.upload]
# The "modules" upload format is required for all projects that implement a Durable Object namespace.
format = "modules"
dir = "worker/generated"
main = "./shim.mjs"

[[build.upload.rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]

[durable_objects]
bindings = [
  { name = "COUNTER", class_name = "Counter" }
]